// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Increment.proto

package com.grpcLib.generatedStubs;

public final class IncrementBuilder {
  private IncrementBuilder() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PresetIncrementRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.protolib.PresetIncrementRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 number = 1;</code>
     * @return The number.
     */
    int getNumber();
  }
  /**
   * Protobuf type {@code com.protolib.PresetIncrementRequest}
   */
  public static final class PresetIncrementRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.protolib.PresetIncrementRequest)
      PresetIncrementRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PresetIncrementRequest.newBuilder() to construct.
    private PresetIncrementRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PresetIncrementRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PresetIncrementRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PresetIncrementRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              number_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpcLib.generatedStubs.IncrementBuilder.internal_static_com_protolib_PresetIncrementRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpcLib.generatedStubs.IncrementBuilder.internal_static_com_protolib_PresetIncrementRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest.class, com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest.Builder.class);
    }

    public static final int NUMBER_FIELD_NUMBER = 1;
    private int number_;
    /**
     * <code>int32 number = 1;</code>
     * @return The number.
     */
    @java.lang.Override
    public int getNumber() {
      return number_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (number_ != 0) {
        output.writeInt32(1, number_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (number_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, number_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest)) {
        return super.equals(obj);
      }
      com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest other = (com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest) obj;

      if (getNumber()
          != other.getNumber()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getNumber();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.protolib.PresetIncrementRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.protolib.PresetIncrementRequest)
        com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.grpcLib.generatedStubs.IncrementBuilder.internal_static_com_protolib_PresetIncrementRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.grpcLib.generatedStubs.IncrementBuilder.internal_static_com_protolib_PresetIncrementRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest.class, com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest.Builder.class);
      }

      // Construct using com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        number_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.grpcLib.generatedStubs.IncrementBuilder.internal_static_com_protolib_PresetIncrementRequest_descriptor;
      }

      @java.lang.Override
      public com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest getDefaultInstanceForType() {
        return com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest build() {
        com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest buildPartial() {
        com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest result = new com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest(this);
        result.number_ = number_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest) {
          return mergeFrom((com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest other) {
        if (other == com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest.getDefaultInstance()) return this;
        if (other.getNumber() != 0) {
          setNumber(other.getNumber());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int number_ ;
      /**
       * <code>int32 number = 1;</code>
       * @return The number.
       */
      @java.lang.Override
      public int getNumber() {
        return number_;
      }
      /**
       * <code>int32 number = 1;</code>
       * @param value The number to set.
       * @return This builder for chaining.
       */
      public Builder setNumber(int value) {
        
        number_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 number = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumber() {
        
        number_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.protolib.PresetIncrementRequest)
    }

    // @@protoc_insertion_point(class_scope:com.protolib.PresetIncrementRequest)
    private static final com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest();
    }

    public static com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PresetIncrementRequest>
        PARSER = new com.google.protobuf.AbstractParser<PresetIncrementRequest>() {
      @java.lang.Override
      public PresetIncrementRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PresetIncrementRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PresetIncrementRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PresetIncrementRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.grpcLib.generatedStubs.IncrementBuilder.PresetIncrementRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DynamicIncrementRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.protolib.DynamicIncrementRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 number = 1;</code>
     * @return The number.
     */
    int getNumber();

    /**
     * <code>int32 step = 2;</code>
     * @return The step.
     */
    int getStep();
  }
  /**
   * Protobuf type {@code com.protolib.DynamicIncrementRequest}
   */
  public static final class DynamicIncrementRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.protolib.DynamicIncrementRequest)
      DynamicIncrementRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DynamicIncrementRequest.newBuilder() to construct.
    private DynamicIncrementRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DynamicIncrementRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DynamicIncrementRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DynamicIncrementRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              number_ = input.readInt32();
              break;
            }
            case 16: {

              step_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpcLib.generatedStubs.IncrementBuilder.internal_static_com_protolib_DynamicIncrementRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpcLib.generatedStubs.IncrementBuilder.internal_static_com_protolib_DynamicIncrementRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest.class, com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest.Builder.class);
    }

    public static final int NUMBER_FIELD_NUMBER = 1;
    private int number_;
    /**
     * <code>int32 number = 1;</code>
     * @return The number.
     */
    @java.lang.Override
    public int getNumber() {
      return number_;
    }

    public static final int STEP_FIELD_NUMBER = 2;
    private int step_;
    /**
     * <code>int32 step = 2;</code>
     * @return The step.
     */
    @java.lang.Override
    public int getStep() {
      return step_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (number_ != 0) {
        output.writeInt32(1, number_);
      }
      if (step_ != 0) {
        output.writeInt32(2, step_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (number_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, number_);
      }
      if (step_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, step_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest)) {
        return super.equals(obj);
      }
      com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest other = (com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest) obj;

      if (getNumber()
          != other.getNumber()) return false;
      if (getStep()
          != other.getStep()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getNumber();
      hash = (37 * hash) + STEP_FIELD_NUMBER;
      hash = (53 * hash) + getStep();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.protolib.DynamicIncrementRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.protolib.DynamicIncrementRequest)
        com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.grpcLib.generatedStubs.IncrementBuilder.internal_static_com_protolib_DynamicIncrementRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.grpcLib.generatedStubs.IncrementBuilder.internal_static_com_protolib_DynamicIncrementRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest.class, com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest.Builder.class);
      }

      // Construct using com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        number_ = 0;

        step_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.grpcLib.generatedStubs.IncrementBuilder.internal_static_com_protolib_DynamicIncrementRequest_descriptor;
      }

      @java.lang.Override
      public com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest getDefaultInstanceForType() {
        return com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest build() {
        com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest buildPartial() {
        com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest result = new com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest(this);
        result.number_ = number_;
        result.step_ = step_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest) {
          return mergeFrom((com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest other) {
        if (other == com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest.getDefaultInstance()) return this;
        if (other.getNumber() != 0) {
          setNumber(other.getNumber());
        }
        if (other.getStep() != 0) {
          setStep(other.getStep());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int number_ ;
      /**
       * <code>int32 number = 1;</code>
       * @return The number.
       */
      @java.lang.Override
      public int getNumber() {
        return number_;
      }
      /**
       * <code>int32 number = 1;</code>
       * @param value The number to set.
       * @return This builder for chaining.
       */
      public Builder setNumber(int value) {
        
        number_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 number = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumber() {
        
        number_ = 0;
        onChanged();
        return this;
      }

      private int step_ ;
      /**
       * <code>int32 step = 2;</code>
       * @return The step.
       */
      @java.lang.Override
      public int getStep() {
        return step_;
      }
      /**
       * <code>int32 step = 2;</code>
       * @param value The step to set.
       * @return This builder for chaining.
       */
      public Builder setStep(int value) {
        
        step_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 step = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStep() {
        
        step_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.protolib.DynamicIncrementRequest)
    }

    // @@protoc_insertion_point(class_scope:com.protolib.DynamicIncrementRequest)
    private static final com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest();
    }

    public static com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DynamicIncrementRequest>
        PARSER = new com.google.protobuf.AbstractParser<DynamicIncrementRequest>() {
      @java.lang.Override
      public DynamicIncrementRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DynamicIncrementRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DynamicIncrementRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DynamicIncrementRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.grpcLib.generatedStubs.IncrementBuilder.DynamicIncrementRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface IncrementReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.protolib.IncrementReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 replyNumber = 1;</code>
     * @return The replyNumber.
     */
    int getReplyNumber();
  }
  /**
   * Protobuf type {@code com.protolib.IncrementReply}
   */
  public static final class IncrementReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.protolib.IncrementReply)
      IncrementReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IncrementReply.newBuilder() to construct.
    private IncrementReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IncrementReply() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new IncrementReply();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IncrementReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              replyNumber_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpcLib.generatedStubs.IncrementBuilder.internal_static_com_protolib_IncrementReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpcLib.generatedStubs.IncrementBuilder.internal_static_com_protolib_IncrementReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply.class, com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply.Builder.class);
    }

    public static final int REPLYNUMBER_FIELD_NUMBER = 1;
    private int replyNumber_;
    /**
     * <code>int32 replyNumber = 1;</code>
     * @return The replyNumber.
     */
    @java.lang.Override
    public int getReplyNumber() {
      return replyNumber_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (replyNumber_ != 0) {
        output.writeInt32(1, replyNumber_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (replyNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, replyNumber_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply)) {
        return super.equals(obj);
      }
      com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply other = (com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply) obj;

      if (getReplyNumber()
          != other.getReplyNumber()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REPLYNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getReplyNumber();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.protolib.IncrementReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.protolib.IncrementReply)
        com.grpcLib.generatedStubs.IncrementBuilder.IncrementReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.grpcLib.generatedStubs.IncrementBuilder.internal_static_com_protolib_IncrementReply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.grpcLib.generatedStubs.IncrementBuilder.internal_static_com_protolib_IncrementReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply.class, com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply.Builder.class);
      }

      // Construct using com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        replyNumber_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.grpcLib.generatedStubs.IncrementBuilder.internal_static_com_protolib_IncrementReply_descriptor;
      }

      @java.lang.Override
      public com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply getDefaultInstanceForType() {
        return com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply.getDefaultInstance();
      }

      @java.lang.Override
      public com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply build() {
        com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply buildPartial() {
        com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply result = new com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply(this);
        result.replyNumber_ = replyNumber_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply) {
          return mergeFrom((com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply other) {
        if (other == com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply.getDefaultInstance()) return this;
        if (other.getReplyNumber() != 0) {
          setReplyNumber(other.getReplyNumber());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int replyNumber_ ;
      /**
       * <code>int32 replyNumber = 1;</code>
       * @return The replyNumber.
       */
      @java.lang.Override
      public int getReplyNumber() {
        return replyNumber_;
      }
      /**
       * <code>int32 replyNumber = 1;</code>
       * @param value The replyNumber to set.
       * @return This builder for chaining.
       */
      public Builder setReplyNumber(int value) {
        
        replyNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 replyNumber = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearReplyNumber() {
        
        replyNumber_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.protolib.IncrementReply)
    }

    // @@protoc_insertion_point(class_scope:com.protolib.IncrementReply)
    private static final com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply();
    }

    public static com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IncrementReply>
        PARSER = new com.google.protobuf.AbstractParser<IncrementReply>() {
      @java.lang.Override
      public IncrementReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IncrementReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IncrementReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IncrementReply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.grpcLib.generatedStubs.IncrementBuilder.IncrementReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protolib_PresetIncrementRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protolib_PresetIncrementRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protolib_DynamicIncrementRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protolib_DynamicIncrementRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protolib_IncrementReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protolib_IncrementReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Increment.proto\022\014com.protolib\"(\n\026Prese" +
      "tIncrementRequest\022\016\n\006number\030\001 \001(\005\"7\n\027Dyn" +
      "amicIncrementRequest\022\016\n\006number\030\001 \001(\005\022\014\n\004" +
      "step\030\002 \001(\005\"%\n\016IncrementReply\022\023\n\013replyNum" +
      "ber\030\001 \001(\0052\226\002\n\017PresetIncrement\022U\n\017increme" +
      "ntByFive\022$.com.protolib.PresetIncrementR" +
      "equest\032\034.com.protolib.IncrementReply\022V\n\020" +
      "incrementBySeven\022$.com.protolib.PresetIn" +
      "crementRequest\032\034.com.protolib.IncrementR" +
      "eply\022T\n\016incrementByTen\022$.com.protolib.Pr" +
      "esetIncrementRequest\032\034.com.protolib.Incr" +
      "ementReply2d\n\020DynamicIncrement\022P\n\tincrem" +
      "ent\022%.com.protolib.DynamicIncrementReque" +
      "st\032\034.com.protolib.IncrementReplyB.\n\032com." +
      "grpcLib.generatedStubsB\020IncrementBuilder" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_protolib_PresetIncrementRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_protolib_PresetIncrementRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protolib_PresetIncrementRequest_descriptor,
        new java.lang.String[] { "Number", });
    internal_static_com_protolib_DynamicIncrementRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_protolib_DynamicIncrementRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protolib_DynamicIncrementRequest_descriptor,
        new java.lang.String[] { "Number", "Step", });
    internal_static_com_protolib_IncrementReply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_protolib_IncrementReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protolib_IncrementReply_descriptor,
        new java.lang.String[] { "ReplyNumber", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
